// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNc_Kgx7DMpvjfuel5bL47fgB_CbWKpGA',
    appId: '1:913532453798:web:57389e81b42986e12a0567',
    messagingSenderId: '913532453798',
    projectId: 'digitalmarketing-e61d0',
    authDomain: 'digitalmarketing-e61d0.firebaseapp.com',
    storageBucket: 'digitalmarketing-e61d0.firebasestorage.app',
    measurementId: 'G-9T3FJLY5C9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNTW3gWDDYGXy3EXQNPwY9Vqksog57Fyc',
    appId: '1:913532453798:android:1356b4124572fe0d2a0567',
    messagingSenderId: '913532453798',
    projectId: 'digitalmarketing-e61d0',
    storageBucket: 'digitalmarketing-e61d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8Vsnlwz7xiarCb2RTRDOM0zfx9S5QT6s',
    appId: '1:913532453798:ios:8dc1ca0924ad78da2a0567',
    messagingSenderId: '913532453798',
    projectId: 'digitalmarketing-e61d0',
    storageBucket: 'digitalmarketing-e61d0.firebasestorage.app',
    iosBundleId: 'com.example.digitalMarketingStratergy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8Vsnlwz7xiarCb2RTRDOM0zfx9S5QT6s',
    appId: '1:913532453798:ios:8dc1ca0924ad78da2a0567',
    messagingSenderId: '913532453798',
    projectId: 'digitalmarketing-e61d0',
    storageBucket: 'digitalmarketing-e61d0.firebasestorage.app',
    iosBundleId: 'com.example.digitalMarketingStratergy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNc_Kgx7DMpvjfuel5bL47fgB_CbWKpGA',
    appId: '1:913532453798:web:a222c209aad455e72a0567',
    messagingSenderId: '913532453798',
    projectId: 'digitalmarketing-e61d0',
    authDomain: 'digitalmarketing-e61d0.firebaseapp.com',
    storageBucket: 'digitalmarketing-e61d0.firebasestorage.app',
    measurementId: 'G-VG3FR5BYRB',
  );
}
